#            --------------------------------------------------------
#            |             Welcome to config NRTP                    |
#            --------------------------------------------------------


random teleport region:
  - 0 # from X
  - 0 # from Z
  - 1000 # to X
  - 1000 # to Z

permission error: 'you do not have permission for this command'
player error: 'there is no such player on the server'
command error: 'you wrote the wrong command'
