name: NRTP
version: '${project.version}'
main: me.niresed.nrtp.NRTP
api-version: 1.16
depend:
  - Towny

commands:
  rtp:
    description: It is random teleport player
    usage: you are teleported

permissions:
  nrtp.rtp:
    description: Access to the ntrp command
    default: op